FROM node:16.15.0

ENV TZ=Asia/Tokyo
ARG USERNAME=node

RUN corepack enable npm
RUN SNIPPET='\n export PROMPT_COMMAND="history -a" && export HISTFILE=/bashlog/.bash_history \n \
            \n if [ "$SHLVL" = "2" ] ; then \n \
            \t script -a -f /bashlog/bash.log \n \
            fi \n' \
  && mkdir /bashlog \
  && touch /bashlog/.bash_history /bashlog/bash.log \
  && chown -R ${USERNAME} /bashlog \
  && echo ${SNIPPET} >> "/home/${USERNAME}/.bashrc"

USER ${USERNAME}
RUN mkdir -p /home/${USERNAME}/.vscode-server/extensions
WORKDIR /myapp-frontend

EXPOSE 3000
