FROM node:16.15.1

ENV TZ=Asia/Tokyo
ARG USERNAME=node

RUN corepack enable npm
RUN SNIPPET='\n if [ "$SHLVL" = "2" ] ; then \n \
            \t script -f /bashlog/script/`date "+%Y%m%d%H%M%S"`.log \n \
            fi \n \
            \n export PROMPT_COMMAND="history -a" && export HISTFILE=/bashlog/.bash_history \n' \
    && mkdir -p /bashlog/script\
    && touch /bashlog/.bash_history \
    && chown -R ${USERNAME} /bashlog \
    && echo ${SNIPPET} >> "/home/${USERNAME}/.bashrc"

USER ${USERNAME}
RUN mkdir -p /home/${USERNAME}/.vscode-server/extensions
WORKDIR /myapp-frontend

EXPOSE 3000
