version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile-vscode
    volumes:
      - sources:/myapp-frontend
      - bashlog:/bashlog
      - vscode-extensions:/home/node/.vscode-server/extensions
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  sources:
  bashlog:
  vscode-extensions:
  